### ISSUE TITLE
why multiple nginx.conf

### ISSUE THREAD

**Issue by hiscal2015** [g17/nginx-ldap#6]
There're two nginx.conf located in / and /etc/nginx/, and nginx was build with --conf-path=/etc/nginx/nginx.conf, but seems only /nginx.conf is the correct entry. After checking your run.sh, /nginx.conf was used by dockerize, but why doing so? Is it better to create a symbol link from /nginx.conf to /etc/nginx/nginx.conf? Thanks.

**Comment by g17** [comment]
I refactored the ```run.sh``` in commit [1dca0bfa9638abee78ab8baf43e153e7222efc72](https://github.com/g17/nginx-ldap/commit/1dca0bfa9638abee78ab8baf43e153e7222efc72). It was a bit odd. It is better to copy the ```/nginx.conf``` (if available) to the path where nginx expects its configuration (```/etc/nginx/nginx.conf```).

**Comment by hiscal2015** [comment]
@g17 I saw your changes, but why not let user mount nginx.conf directly to /etc/nginx/nginx.conf? You know it's impossible to mount files to / in Kubernetes environment.
